### PR TITLE
added stats calculations to MatchView

### PR DESCRIPTION
**Pull request by wchen27**
Added the calculations of winrate and trophies gained in the past matches to the MatchView. In addition, cleaned up the look of the MatchView.

### CODE REVIEW

**Comment by dujstn** [comment]
looks good :) do you handle the case when the api isn't returning correctly (i.e. number of matches is 0?)

**Comment by wchen27** [comment]
great catch! i'll add in that test case now.

**Comment by dujstn** [comment]
sounds good!

**Comment by wchen27** [comment]
should be fixed, please take another look :)

**Comment by dujstn** [comment]
looks awesome!

**Pull request merged**
