### PR TITLE
Finished previous_search usecase

### PR DESCRIPTION
**Pull request by Thigamore**

### CODE REVIEW

**Comment by dujstn** [comment]
Looks cool! Did you adjust the home page view as well?

**Comment by Thigamore** [comment]
This use case is primarily for the home view to show the previous searches.

**Comment by dujstn** [comment]
Wait I just tried to run it and it's not working yet. any ideas on why?

**Comment by Thigamore** [comment]
I think I may have forgotten a line for the add Previous Search. let me add it real quick

**Comment by dujstn** [comment]
Ok cool ;)

**Review by harrypenguin — CHANGES_REQUESTED** [review]
To properly store the previous searches, you should make it so that every time you call `APIDataAccessObject`, it is added to a file.

**Comment by harrypenguin** [comment]
Looks good now! Will merge you.

**Review by harrypenguin — APPROVED** [review]
Looks good, will merge you now

**Pull request merged**
