### PR TITLE
codebase file cleanup

### PR DESCRIPTION
**Pull request by dujstn**
Removed associated brawler search files

### CODE REVIEW

**Comment by wchen27** [comment]
Looking good. Does removing the Brawler Search button from the home screen change the layout significantly at all?

**Comment by wchen27** [comment]
Also would it be possible to cleanly remove Brawler and BrawlerFactory from the entity folder?

**Comment by dujstn** [comment]
> Looking good. Does removing the Brawler Search button from the home screen change the layout significantly at all?

I'll remove it to maintain functionality of the application. We can add it back later



> Also would it be possible to cleanly remove Brawler and BrawlerFactory from the entity folder?

Forgot to remove those as well. Thanks for catching that :)

**Comment by dujstn** [comment]
fixed but one of the tests is no longer running. any thoughts?

**Comment by wchen27** [comment]
which test? could you be a bit more specific

**Comment by wchen27** [comment]
Seemed to have caught the bug. You need to add a dummy api key into test.env, and then the test passes. Going to merge if there are no other isseus 👍

**Pull request merged**
